const questions = [
    {
      question: "What is data in motion?",
      options: [
        "Value extracted from data while it is being generated",
        "Data stored in mobile devices",
        "Data generated by an IoT device that is moving",
        "Data transferred from an IoT device to the cloud",
      ],
      answer: [0],
    },
    {
      question: "Which statement is an accurate description of 4G and 5G wireless technologies?",
      options: [
        "Both use a low-energy, low-power, low-data rate for wireless personal-area networks.",
        "They require a wireless WAN connection to power-constricted devices.",
        "They are both cellular-based technologies for covering large geographic areas.",
        "They both require a 2.4 GHz short-range radio frequency band for industrial, scientific, and medical applications.",
      ],
      answer: [2],
    },
    {
      question: "Fill in the blank:\nThe three Vs that distinguish data from big data are velocity, volume, and variety.",
      options: [],
      answer: null,
    },
    {
      question: "What are three characteristics that distinguish big data from data? (Choose three.)",
      options: [
        "Amount of data being transported and stored",
        "Rate at which data is generated",
        "Type of data that is generated",
        "Where the data is stored",
        "How the data is collected",
        "Who is authorized to access the data",
      ],
      answer: [0, 1, 2], // Multiple correct answers
    },
    {
      question: "Which wireless technology has low-power and data rate requirements, making it popular in home automation applications?",
      options: ["LoRaWAN", "5G", "Wi-Fi", "ZigBee"],
      answer: [3],
    },
    {
      question: "Which pillar of the Cisco IoT System allows data to be analyzed and managed at the location where it is generated?",
      options: ["Data analytics", "Fog computing", "Network connectivity", "Application enhancement platform"],
      answer: [1],
    },
    {
      question: "Match the wireless technology with the description:\nZigBee → Popular in IoT applications such as home automation\n4G/5G → Cellular-based technology for transferring data over large geographic areas\nLoRaWAN → Uses a gateway to relay messages between end-devices and a central network server",
      options: [],
      answer: null,
    },
    {
      question: "Which wireless technology can be used to provide a metropolitan area with up to 100 Mbps of bandwidth?",
      options: ["Bluetooth", "5G", "LoRaWAN", "ZigBee"],
      answer: [1],
    },
    {
      question: "Which cloud service provides an app development platform and a backend service for apps?",
      options: ["Built.io", "Zapier", "IFTTT", "ZigBee"],
      answer: [0],
    },
    {
      question: "Match the type of media with the transmission technology:\nCopper wires → Electrical impulses\nFiber optic cable → Pulses of light\nWireless → Radio waves",
      options: [],
      answer: null,
    },
    {
      question: "What are two protocols developed by the Wi-Fi Alliance to secure wireless networks? (Choose two.)",
      options: ["WPA", "802.1x", "WPA2", "LoRaWAN", "IPsec"],
      answer: [0, 2], // Multiple correct answers
    },
    {
        question: "Match the network component category with the description:",
        options: [
          "End devices → Source or destination of a message",
          "Intermediate devices → Determine the best path for packets",
          "Media → Physical channel to carry messages",
          "Services → Network applications",
        ],
        answer: [0, 1, 2, 3], // Correct order
        type: "match", // Indicate it's a matching question
    },
    {
      question: "Which type of payment model is typically used to purchase cloud services?",
      options: ["Annual subscription fee", "Lump-sum payment in advance", "Pay-as-you-go system", "Calculation based on bandwidth"],
      answer: [2],
    },
    {
      question: "What are rules governing communication between network devices?",
      options: ["Processes", "Protocols", "Services", "Architectures"],
      answer: [1],
    },
    {
      question: "What measure should be taken to secure IoT devices?",
      options: [
        "Install self-encrypting hard drives",
        "Disconnect from the Internet",
        "Keep firmware updated",
        "Implement the security-through-obscurity model",
      ],
      answer: [2],
    },
    {
      question: "What is the goal of fog computing?",
      options: [
        "To store all data on a single server for processing",
        "To send data immediately to the cloud for secure storage",
        "To analyze data as close to the source as possible",
        "To permanently store data on the local device",
      ],
      answer: [2],
    },
    {
      question: "Fill in the blank:\nA wide-area network (WAN) is usually administered by multiple service providers.",
      options: [],
      answer: null,
    },
    {
      question: "Fill in the blank:\nA local-area network (LAN) is a network infrastructure that interconnects end devices in a limited area.",
      options: [],
      answer: null,
    },
    {
      question: "What is the role of routing on data networks?",
      options: [
        "To determine the best paths for packets through the network",
        "To provide a physical channel for packets to travel through the network",
        "To ensure the availability of services and resources on the network",
        "To provide an architecture for data exchange",
      ],
      answer: [0],
    },
    {
        question: "What tool can be used on a Linux device to compare all installed software against a repository index, to download updates, and to install them automatically?",
        options: [
          "Blockly",
          "Improved C Shell (tcsh)",
          "Arduino",
          "Package manager system",
        ],
        answer: [3],
      },
      {
        question: "A user is using Blockly to program a process to find the next 100 prime numbers after 2. Which block is best used for the task?",
        options: [
          "FOR block",
          "WHILE block",
          "PRIME block",
          "IF-THEN block",
        ],
        answer: [0],
      },
      {
        question: "What elements are used to represent different programming structures in Blockly?",
        options: [
          "Flowcharts",
          "Colored blocks",
          "Programming code pieces",
          "Colored lines and symbols",
        ],
        answer: [1],
      },
      {
        question: "True or False? Programmers only work on desktop applications.",
        options: ["True", "False"],
        answer: [1],
      },
      {
        question: "Which Python function is used for console output?",
        options: [
          "Print",
          "Return",
          "For",
          "From",
        ],
        answer: [0],
      },
      {
        question: "What is a Raspberry Pi?",
        options: [
          "A small, low-cost, single-board computer",
          "A Python function for conditional logic",
          "An object-oriented programming language",
          "A cloud-based service for teaching IoT",
        ],
        answer: [0],
      },
      {
        question: "Which statement describes Blockly?",
        options: [
          "It is a compiled language.",
          "It is a specific Linux distribution.",
          "It is graphic editing software for web design.",
          "It is a JavaScript-based library for implementing visual programming.",
        ],
        answer: [3],
      },
      {
        question: "What are two features related to Linux? (Choose two.)",
        options: [
          "Open source",
          "An application for word processing",
          "An example of interpreted language",
          "A code base managed by one organization",
          "Support by a community of programmers",
        ],
        answer: [0, 4],
      },
      {
        question: "Which language is an example of a compiled programming language?",
        options: [
          "Python",
          "PHP",
          "Javascript",
          "C",
        ],
        answer: [3],
      },
      {
        question: "A system administrator issues the command ps on a server that is running the Linux operating system. What is the purpose of this command?",
        options: [
          "To process a new task",
          "To change file permissions",
          "To display the contents of the current directory",
          "To list the processes currently running in the system",
        ],
        answer: [3],
      },
      {
        question: "Which Linux shell command can be used to search for a specific string of characters within a file?",
        options: [
          "Cat",
          "Man",
          "Pwd",
          "Grep",
        ],
        answer: [3],
      },
      {
        question: "What is needed for a computer program to communicate with another computer program made from a different vendor?",
        options: [
          "API",
          "Firmware",
          "Device driver",
          "Operating system",
        ],
        answer: [0],
      },
      {
        question: "What is the benefit of deploying a group of headless Pi IoT devices?",
        options: [
          "Each Pi IoT device is managed remotely on a network.",
          "A single monitor can be connected to the group of Pi IoT devices.",
          "The Pi IoT devices can connect to each other using Zigbee.",
          "The group of Pi IoT devices must be controlled by a single Pi device in the cloud.",
        ],
        answer: [0],
      },
      {
        question: "Which Python command is an example of conditional logic?",
        options: [
          "Def",
          "Delay",
          "If",
          "From",
        ],
        answer: [2],
      },
      {
        question: "Why is it common to connect an Arduino board with a single-board computer like the Raspberry Pi?",
        options: [
          "The Arduino is a full computer and the Raspberry Pi is not.",
          "The Raspberry Pi cannot process incoming digital signals.",
          "The Arduino has analog pins.",
          "The Raspberry Pi does not require software to interact with an Arduino.",
        ],
        answer: [2],
      },
      {
        question: "What is an advantage of an executable program coded with an interpreted language compared with a compiled language?",
        options: [
          "It runs faster.",
          "It stores as binary format.",
          "It is easier to maintain and troubleshoot.",
          "It does not rely on another program in order to execute.",
        ],
        answer: [2],
      },
      {
        question: "What is a method to secure the control plane of an IoT device?",
        options: [
          "The encryption of user data",
          "Enforcement of authorized access to code",
          "Restricting access to servers",
          "Verification of data integrity",
        ],
        answer: [1],
      },
      {
        question: "Which Linux distribution is used to develop the Raspbian operating system for the Raspberry Pi?",
        options: [
          "Mint",
          "Ubuntu",
          "Debian",
          "Red Hat",
          "Slackware",
        ],
        answer: [2],
      },
      
  {
    question: "What tool can be used on a Linux device to compare all installed software against a repository index, to download updates, and to install them automatically?",
    options: [
      "Blockly",
      "Improved C Shell (tcsh)",
      "Arduino",
      "Package manager system",
    ],
    answer: [3],
  },
  {
    question: "A user is using Blockly to program a process to find the next 100 prime numbers after 2. Which block is best used for the task?",
    options: [
      "FOR block",
      "WHILE block",
      "PRIME block",
      "IF-THEN block",
    ],
    answer: [0],
  },
  {
    question: "What elements are used to represent different programming structures in Blockly?",
    options: [
      "Flowcharts",
      "Colored blocks",
      "Programming code pieces",
      "Colored lines and symbols",
    ],
    answer: [1],
  },
  {
    question: "True or False? Programmers only work on desktop applications.",
    options: ["True", "False"],
    answer: [1],
  },
  {
    question: "Which Python function is used for console output?",
    options: [
      "Print",
      "Return",
      "For",
      "From",
    ],
    answer: [0],
  },
  {
    question: "What is a Raspberry Pi?",
    options: [
      "A small, low-cost, single-board computer",
      "A Python function for conditional logic",
      "An object-oriented programming language",
      "A cloud-based service for teaching IoT",
    ],
    answer: [0],
  },
  {
    question: "Which statement describes Blockly?",
    options: [
      "It is a compiled language.",
      "It is a specific Linux distribution.",
      "It is graphic editing software for web design.",
      "It is a JavaScript-based library for implementing visual programming.",
    ],
    answer: [3],
  },
  {
    question: "What are two features related to Linux? (Choose two.)",
    options: [
      "Open source",
      "An application for word processing",
      "An example of interpreted language",
      "A code base managed by one organization",
      "Support by a community of programmers",
    ],
    answer: [0, 4],
  },
  {
    question: "Which language is an example of a compiled programming language?",
    options: [
      "Python",
      "PHP",
      "Javascript",
      "C",
    ],
    answer: [3],
  },
  {
    question: "A system administrator issues the command ps on a server that is running the Linux operating system. What is the purpose of this command?",
    options: [
      "To process a new task",
      "To change file permissions",
      "To display the contents of the current directory",
      "To list the processes currently running in the system",
    ],
    answer: [3],
  },
  {
    question: "Which Linux shell command can be used to search for a specific string of characters within a file?",
    options: [
      "Cat",
      "Man",
      "Pwd",
      "Grep",
    ],
    answer: [3],
  },
  {
    question: "What is needed for a computer program to communicate with another computer program made from a different vendor?",
    options: [
      "API",
      "Firmware",
      "Device driver",
      "Operating system",
    ],
    answer: [0],
  },
  {
    question: "What is the benefit of deploying a group of headless Pi IoT devices?",
    options: [
      "Each Pi IoT device is managed remotely on a network.",
      "A single monitor can be connected to the group of Pi IoT devices.",
      "The Pi IoT devices can connect to each other using Zigbee.",
      "The group of Pi IoT devices must be controlled by a single Pi device in the cloud.",
    ],
    answer: [0],
  },
  {
    question: "Which Python command is an example of conditional logic?",
    options: [
      "Def",
      "Delay",
      "If",
      "From",
    ],
    answer: [2],
  },
  {
    question: "Why is it common to connect an Arduino board with a single-board computer like the Raspberry Pi?",
    options: [
      "The Arduino is a full computer and the Raspberry Pi is not.",
      "The Raspberry Pi cannot process incoming digital signals.",
      "The Arduino has analog pins.",
      "The Raspberry Pi does not require software to interact with an Arduino.",
    ],
    answer: [2],
  },
  {
    question: "What is an advantage of an executable program coded with an interpreted language compared with a compiled language?",
    options: [
      "It runs faster.",
      "It stores as binary format.",
      "It is easier to maintain and troubleshoot.",
      "It does not rely on another program in order to execute.",
    ],
    answer: [2],
  },
  {
    question: "What is a method to secure the control plane of an IoT device?",
    options: [
      "The encryption of user data",
      "Enforcement of authorized access to code",
      "Restricting access to servers",
      "Verification of data integrity",
    ],
    answer: [1],
  },
  {
    question: "Which Linux distribution is used to develop the Raspbian operating system for the Raspberry Pi?",
    options: [
      "Mint",
      "Ubuntu",
      "Debian",
      "Red Hat",
      "Slackware",
    ],
    answer: [2],
  },
  {
    question: "How are electronic sensors used in digitizing the natural world?",
    options: [
      "They measure a physical event and translate it into electrical signals",
      "They measure voltage as a function of time and output a graph",
      "They convert digital events into analog representations",
      "They measure electrical signals sent from a specific computer port",
    ],
    answer: [0],
  },
  {
    question: "What type of electrical circuit stops working when a single electronic component is damaged or removed?",
    options: [
      "series",
      "nonlinear",
      "parallel",
      "linear",
    ],
    answer: [0],
  },
  {
    question: "What is used to limit the amount of current that flows through the circuit?",
    options: [
      "resistor",
      "inductor",
      "capacitor",
      "LED",
    ],
    answer: [0],
  },
  {
    question: "What is another term for an electrically controlled mechanical switch?",
    options: [
      "relay",
      "microcontroller",
      "actuator",
      "sensor",
    ],
    answer: [0],
  },
  {
    question: "What software package is commonly used to create programs for the Arduino?",
    options: [
      "Arduino IDE",
      "Packet Tracer",
      "SparkFun",
      "RedBoard",
    ],
    answer: [0],
  },
  {
    question: "Which tool measures the ratio of voltage to current across an object?",
    options: [
      "multimeter",
      "clamp meter",
      "oscilloscope",
      "wattmeter",
    ],
    answer: [0],
  },
  {
    question: "Fill in the blank. The graphic shows an example of a simple ___",
    options: [
      "circuit",
      "None",
    ],
    answer: [0],
  },
  {
    question: "Which two technologies are considered 4th generation cellular-based technologies that commonly require monthly payments to connect IoT devices? (Choose two.)",
    options: [
      "LOWARAN",
      "WiMAX",
      "ZigBee",
      "Bluetooth",
      "LTE",
    ],
    answer: [1, 4],
},
  {
    question: "What is direct current?",
    options: [
      "the type of current that is produced by batteries, computer power supplies, and solar cells",
      "the type of current that is supplied to the home by power utilities",
      "the type of electric current in which the current flow periodically reverses direction",
      "the type of current that is represented by a sine wave",
    ],
    answer: [0],
  },
  {
    question: "Which three items can serve as inputs to a microcontroller unit such as an Arduino? (Choose three.)",
    options: [
      "a sensor",
      "a pushbutton",
      "a relay",
      "an LED",
      "a Twitter message",
      "an actuator",
    ],
    answer: [0, 1, 5],
  },
  {
    question: "Match the unit of measurement with the associated electronic concept.",
    options: [
      "watt → power",
      "ampere → current",
      "volt → voltage",
      "ohm → resistance",
      "bandwidth",
      "latency",
    ],
    answer: [0, 1, 2, 3],
  },
  {
    question: "Which tool has the ability to measure the signals that travel from sensors to microcontrollers as a function of time?",
    options: [
      "oscilloscope",
      "multimeter",
      "clamp meter",
      "wattmeter",
    ],
    answer: [0],
  },
  {
    question: "Match the definitions with the appropriate steps of the design phase of a printed circuit board.",
    options: [
      "finding possible vendors and material costs → research",
      "the initial idea → concept",
      "symbolic representations of the circuit and components → circuit design",
    ],
    answer: [0, 1, 2],
  },
  {
    question: "What type of circuit provides multiple paths for current flow so that the failure of a single component will not affect the operation of the entire circuit?",
    options: [
      "parallel",
      "series",
      "linear",
      "nonlinear",
    ],
    answer: [0],
  },
  {
    question: "What type of component is represented if it appeared on an electronic schematic?",
    options: [
      "LED",
      "inductor",
      "resistor",
      "capacitor",
    ],
    answer: [0],
  },
  {
    question: "What is a feature of microcontrollers that makes them well-suited for use in the Internet of Things?",
    options: [
      "low power requirements",
      "large data storage capacity",
      "multiple processor cores",
      "large form factor",
    ],
    answer: [0],
  },
  {
    question: "What type of device is able to create physical movement?",
    options: [
      "actuator",
      "sensor",
      "diode",
      "resistor",
    ],
    answer: [0],
  },
  {
    question: "What functions do sensors perform in the digitized world?",
    options: [
      "detecting events in the physical environment",
      "creating physical movement",
      "performing physical actions",
      "reducing current flow through a circuit",
    ],
    answer: [0],
  },
  {
    question: "What file extension is used when saving sketches written with the Arduino IDE?",
    options: [
      ".txt",
      ".doc",
      ".ino",
      ".exe",
    ],
    answer: [2],
  },
  {
    question: "What type of component has no effect on gain or control over voltage or current?",
    options: [
      "passive",
      "linear",
      "nonlinear",
      "active",
    ],
    answer: [0],
  }

  ];
  
  const quizContainer = document.getElementById("quiz-container");

// Load sounds
const correctSound = document.getElementById("correct-sound");
const wrongSound = document.getElementById("wrong-sound");

questions.forEach((q, index) => {
  const questionDiv = document.createElement("div");
  questionDiv.classList.add("question");

  const questionText = document.createElement("h3");
  questionText.textContent = `${index + 1}. ${q.question}`;
  questionDiv.appendChild(questionText);

  const optionsDiv = document.createElement("div");
  optionsDiv.classList.add("options");

  if (q.type === "match") {
    // If it's a matching question
    const matchingContainer = document.createElement("div");
    matchingContainer.classList.add("matching-container");

    q.options.forEach((option, i) => {
      const optionDiv = document.createElement("div");
      optionDiv.classList.add("matching-option");
      optionDiv.textContent = option;
      matchingContainer.appendChild(optionDiv);
    });

    optionsDiv.appendChild(matchingContainer);
  } else {
    q.options.forEach((option, i) => {
      const button = document.createElement("button");
      button.textContent = option;

      button.addEventListener("click", () => {
        if (q.answer.includes(i)) {
          button.classList.add("correct");
          correctSound.play();
        } else {
          button.classList.add("wrong");
          wrongSound.play();
        }

        button.disabled = true; // Disable the button after clicking

        // Check if all correct answers are selected
        const selectedCorrect = Array.from(optionsDiv.children).filter(
          (btn) => btn.classList.contains("correct")
        ).length;

        if (selectedCorrect === q.answer.length) {
          // Disable all buttons when all correct answers are selected
          Array.from(optionsDiv.children).forEach((btn) => {
            btn.disabled = true;
          });
        }
      });

      optionsDiv.appendChild(button);
    });
  }

  questionDiv.appendChild(optionsDiv);
  quizContainer.appendChild(questionDiv);
});